server:
  #启动端口
  port: 8899
  #项目根路径
  servlet:
    context-path: /service
#启动环境
spring:
  profiles:
    active: dev

#mongodb默认属性配置
  data:
    mongodb:
      host: 192.168.0.50
      port: 27017
      database: testMongo
