#定义当前配置环境
spring:
  profiles:
    active: dev

logging:
  config: classpath:logCfg/logback-${spring.profiles.active}.xml

#自定义配置文件,后续用于加载成JavaBean
project:
  users:
    - {name: zhangsan,password: zs123,uname: 天上的云}
    - {name: lisi,password: ls123,uname: 地上的草}

