spring:
  profiles:
    active: dev
logging:
  config: classpath:logCfg/logback-${spring.profiles.active}.xml
project:
  users:
    - {name: zhangsan,password: zs123,uname: 天上的云}
    - {name: lisi,password: ls123,uname: 地上的草}
