#定义当前配置环境
spring:
  profiles:
    active: dev
#配置日志配置路径使用${spring.profiles.active}动态加载Log配置
logging:
  config: classpath:logCfg/logback-${spring.profiles.active}.xml
#自定义配置文件,后续用于加载成JavaBean
project:
  users:
    - {name: zhangsan,password: zs123,uname: 天上的云}
    - {name: lisi,password: ls123,uname: 地上的草}
jedis:
  database: 0
  port: 6379
  timeout: 1000
  host: 192.168.84.8
  max-active: 100 #连接池最大连接数
  max-wait: -1 #连接池最大阻塞等待时间（负值表示没有限制）
  max-idle: 8 #连接池最大空闲连接
  min-idle: 0 #连接池最小空闲连接
